### ISSUE TITLE
。

### ISSUE THREAD

**Issue by GOUAIAI** [WangJW424/ESPReader#1]

**Comment by WangJW424** [comment]
请问你用的是什么数据集？

**Comment by wanglewoba** [comment]
CMRC2018啊https://github.com/ymcui/cmrc2018/tree/master/data

**Comment by WangJW424** [comment]
我的代码和模型已经过多次验证，请按照我们提供的README.MD运行。如仍有问题可以发邮件至wjw_sjt@sjtu.edu.cn，我们可以提供我们用所给设置训练好的模型。

**Comment by wanglewoba** [comment]
很抱期打扰到您，已经解决
